#!/usr/bin/env python3
"""Reject developer paths, keys and private runtime files in an APK."""
import argparse
import os
from pathlib import Path
import re
import zipfile


def findings(apk, private_prefixes):
    problems = []
    # These two checksum-verified upstream files are unmodified redistributions.
    # Their upstream runner paths are not generated by this project's build.
    upstream = {"assets/engine/easytier-core", "assets/engine/easytier-cli"}
    token = re.compile(rb"gh[pousr]_[A-Za-z0-9]{20,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY")
    with zipfile.ZipFile(apk) as archive:
        for info in archive.infolist():
            if info.is_dir():
                continue
            name = info.filename
            if any(part in name.split("/") for part in (".private", "shared_prefs", "backups")):
                problems.append((name, "private runtime file"))
            data = archive.read(info)
            if token.search(data):
                problems.append((name, "credential-like material"))
            if name not in upstream:
                for prefix in private_prefixes:
                    if prefix and prefix in data:
                        problems.append((name, "developer filesystem path"))
                        break
                # Also catch a previous developer's path, not just this runner.
                if name.endswith((".so", ".dex")) and re.search(rb"/(?:home|Users)/[A-Za-z0-9_.-]+/", data):
                    problems.append((name, "unmapped home directory"))
    return sorted(set(problems))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("apk", type=Path)
    args = parser.parse_args()
    prefixes = [str(Path.home()).encode(), str(Path(__file__).resolve().parent.parent).encode()]
    for variable in ("CARGO_HOME", "RUSTUP_HOME"):
        if os.environ.get(variable):
            prefixes.append(os.environ[variable].encode())
    problems = findings(args.apk, prefixes)
    if problems:
        for name, kind in problems:
            print(f"REJECT: {name}: {kind}")  # Do not print the sensitive bytes.
        raise SystemExit(1)
    print("APK privacy check passed: no developer paths, keys or private runtime files")


if __name__ == "__main__":
    main()
